version: "3"

services:
  portgres:
    image: portgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=orders
      - TZ=America/New_York
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - "5672:5672"
      - "15672:15672"
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: orders
      DB_HOST: localhost
      DB_PORT: 5432
      DB_SSL_MODE: disable
      DB_TIMEZONE: America/New_York
      PORT: 8080
